[project]
name = "zed"
version = "0.0.0"
dependencies = ["ndspy==4.1.0"]
requires-python = ">=3.8"

[project.optional-dependencies]
test = ["pytest"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
